language: node_js
dist: trusty
sudo: required
node_js:
  - "8"

addons:
    chrome: stable

before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3 # give xvfb some time to start
env:
  matrix:
    - MODULE=alfresco-modeler-app

jobs:
    include:
        - stage: Community build and Enterprise update
          script: npm run lint && npm run package:sdk
          name: Lint & Package SDK

        - script:
          - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
          - ./scripts/build-pipeline/update-enterprise.sh -b $BRANCH -c $BRANCH -n $BUILD_REPO_NAME -t $BUILD_GITHUB_TOKEN
          name: Notify Enterprise to update

# Send coverage data to codecov
# after_success:
#   bash <(curl -s https://codecov.io/bash) -X gcov

cache:
  directories:
  - alfresco-modeler-app/node_modules
