language: node_js
dist: trusty
sudo: required
node_js:
  - "12.13.1"

addons:
    chrome: stable

before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3 # give xvfb some time to start
env:
  matrix:
    - MODULE=alfresco-modeler-app

jobs:
    include:
        - stage: Community build and Enterprise update
          script: npm run lint
          name: Lint & Package SDK

# Send coverage data to codecov
# after_success:
#   bash <(curl -s https://codecov.io/bash) -X gcov

cache:
  directories:
  - alfresco-modeler-app/node_modules
